services:
  mssql-2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-2022
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd123
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-2022-data:/var/opt/mssql

volumes:
  mssql-2022-data:
