services:
  mongodb-8:
    image: mongo:8
    container_name: mongodb-8
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=P@ssw0rd123
    volumes:
      - data:/data/db
      - config:/data/configdb

volumes:
  data:
  config:
