services:
  redis-8:
    image: redis:8
    container_name: redis-8
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "6379:6379"
    volumes:
      - data:/data
    environment:
      REDIS_PASSWORD: "P@ssw0rd123"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]

volumes:
  data:
