services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd123
    ports:
      - "3000:3000"
    volumes:
      - data:/var/lib/grafana

volumes:
  data:
