services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
