services:
  postgres-18:
    image: postgres:18
    container_name: postgres-18
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql

volumes:
  data:
