services:
  mysql-8:
    image: mysql:8
    container_name: mysql-8
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd123
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
